# Generated by Django 5.1.7 on 2025-04-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
