# Generated by Django 5.1.7 on 2025-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
